services:
  # Reverse Proxy und Web-Server
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - caddy:/data
      - ./srv:/srv

  # Kalender-Manager
  calunite:
    image: jojodicus/calunite
    container_name: calunite
    restart: unless-stopped
    volumes:
      - ./calunite:/config/
    networks:
      - caddy

networks:
  caddy:
    driver: bridge

volumes:
  caddy:
